version: '3.9'
services:
  noti:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/noti/src
    expose:
      - '3001'
    networks:
      - ticket

networks:
  ticket:
    name: ticketingnetwork
